RENAME TABLE `branchedittable` TO `branchedit`;
RENAME TABLE `branchexportoperationtable` TO `branchexportoperation`;
RENAME TABLE `branchexporttable` TO `branchexport`;
RENAME TABLE `branchimportoperationtable` TO `branchimportoperation`;
RENAME TABLE `branchimporttable` TO `branchimport`;
RENAME TABLE `branchpaymentoperationtable` TO `branchpaymentoperation`;
RENAME TABLE `branchtable` TO `branch`;
RENAME TABLE `customeraccounttransfertable` TO `customeraccounttransfer`;
RENAME TABLE `customeredittable` TO `customeredit`;
RENAME TABLE `customertable` TO `customer`;
RENAME TABLE `expensetable` TO `expense`;
RENAME TABLE `expensetypetable` TO `expensetype`;
RENAME TABLE `paymentaccountedittable` TO `paymentaccountedit`;
RENAME TABLE `paymentaccountoperationtable` TO `paymentaccountoperation`;
RENAME TABLE `paymentaccounttable` TO `paymentaccount`;
RENAME TABLE `productcategorytable` TO `productcategory`;
RENAME TABLE `producthistorytable` TO `producthistory`;
RENAME TABLE `productpricetable` TO `productprice`;
RENAME TABLE `productpricetypetable` TO `productpricetype`;
RENAME TABLE `productstockadjustmenttable` TO `productstockadjustment`;
RENAME TABLE `productstockdeadtable` TO `productstockdead`;
RENAME TABLE `productstocktable` TO `productstock`;
RENAME TABLE `productstocktransfertable` TO `productstocktransfer`;
RENAME TABLE `productstockvaluetable` TO `productstockvalue`;
RENAME TABLE `producttable` TO `product`;
RENAME TABLE `purchasehistorytable` TO `purchasehistory`;
RENAME TABLE `purchasesreturnhistorytable` TO `purchasesreturnhistory`;
RENAME TABLE `purchasesreturntable` TO `purchasesreturn`;
RENAME TABLE `purchasestable` TO `purchases`;
RENAME TABLE `saleshistorytable` TO `saleshistory`;
RENAME TABLE `salesreturnhistorytable` TO `salesreturnhistory`;
RENAME TABLE `salesreturntable` TO `salesreturn`;
RENAME TABLE `salestable` TO `sales`;
RENAME TABLE `settingstable` TO `settings`;
RENAME TABLE `shelftable` TO `shelf`;
RENAME TABLE `stockhistorytable` TO `stockhistory`;
RENAME TABLE `supplieredittable` TO `supplieredit`;
RENAME TABLE `suppliertable` TO `supplier`;
RENAME TABLE `userpermissiontable` TO `userpermission`;
RENAME TABLE `usertable` TO `user`;
START TRANSACTION;
ALTER TABLE `branch` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branch` MODIFY COLUMN `Name` longtext;
ALTER TABLE `branch` MODIFY COLUMN `Phone` longtext;
ALTER TABLE `branch` MODIFY COLUMN `Email` longtext;
ALTER TABLE `branch` MODIFY COLUMN `Address` longtext;
ALTER TABLE `branch` MODIFY COLUMN `OpenningBalance` decimal(18,2) NOT NULL;
ALTER TABLE `branch` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `branch` MODIFY COLUMN `CreatedOn` datetime;
ALTER TABLE `branchedit` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchedit` MODIFY COLUMN `Branch_Id` longtext;
ALTER TABLE `branchedit` MODIFY COLUMN `Initial_Balance` decimal(18,2) NOT NULL;
ALTER TABLE `branchedit` MODIFY COLUMN `Adjusted_Amount` decimal(18,2) NOT NULL;
ALTER TABLE `branchexport` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchexport` MODIFY COLUMN `BranchId` longtext;
ALTER TABLE `branchexportoperation` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchexportoperation` ADD COLUMN `RefId` longtext;
ALTER TABLE `branchexportoperation` MODIFY COLUMN `ProductCode` longtext;
ALTER TABLE `branchexportoperation` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `branchexportoperation` MODIFY COLUMN `Cost` decimal(18,2) NOT NULL;
ALTER TABLE `branchexportoperation` MODIFY COLUMN `Available_Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `branchimport` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchimport` MODIFY COLUMN `BranchId` longtext;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchimportoperation` ADD COLUMN `RefId` longtext;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `ProductCode` longtext;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Available_Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `ReorderLevel` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Cost` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Price1` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Price2` decimal(18,2) NOT NULL;
ALTER TABLE `branchimportoperation` MODIFY COLUMN `Price3` decimal(18,2) NOT NULL;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `Description` longtext;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `PaymentAccountId` longtext;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `BranchAccountId` longtext;
ALTER TABLE `branchpaymentoperation` ADD COLUMN `RefId` longtext;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `TransactionType` longtext;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `PaymentAccountBalance` decimal(18,2) NOT NULL;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `BranchBalance` decimal(18,2) NOT NULL;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `CreatedOn` datetime;
ALTER TABLE `branchpaymentoperation` MODIFY COLUMN `IsCredit` tinyint(1) NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `Name` longtext;
ALTER TABLE `customer` MODIFY COLUMN `Phone` longtext;
ALTER TABLE `customer` MODIFY COLUMN `Email` longtext;
ALTER TABLE `customer` MODIFY COLUMN `Address` longtext;
ALTER TABLE `customer` MODIFY COLUMN `OpenningBalance` decimal(18,2) NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `CreditAllowanceDays` int(11) NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `LastModifiedOn` datetime NOT NULL;
ALTER TABLE `customer` MODIFY COLUMN `Active` tinyint(1) NOT NULL;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `Description` longtext;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `FromAccountId` longtext;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `ToAccountId` longtext;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `FromBalance` decimal(18,2) NOT NULL;
ALTER TABLE `customeraccounttransfer` MODIFY COLUMN `ToBalance` decimal(18,2) NOT NULL;
ALTER TABLE `customeredit` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `customeredit` MODIFY COLUMN `Customer_Id` longtext;
ALTER TABLE `customeredit` MODIFY COLUMN `Initial_Balance` decimal(18,2) NOT NULL;
ALTER TABLE `customeredit` MODIFY COLUMN `Adjusted_Amount` decimal(18,2) NOT NULL;
ALTER TABLE `expense` MODIFY COLUMN `InvoiceNumber` varchar(128) NOT NULL;
ALTER TABLE `expense` MODIFY COLUMN `Type` longtext;
ALTER TABLE `expense` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `expense` MODIFY COLUMN `Purpose` longtext;
ALTER TABLE `expense` MODIFY COLUMN `PaidInto` longtext;
ALTER TABLE `expense` MODIFY COLUMN `ApprovedBy` longtext;
ALTER TABLE `expense` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `expense` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `expensetype` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `expensetype` MODIFY COLUMN `Name` longtext;
ALTER TABLE `expensetype` MODIFY COLUMN `Description` longtext;
ALTER TABLE `expensetype` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `paymentaccount` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `paymentaccount` MODIFY COLUMN `Type` int(11) NOT NULL;
ALTER TABLE `paymentaccount` MODIFY COLUMN `AccountNo` varchar(15);
ALTER TABLE `paymentaccount` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccount` MODIFY COLUMN `OpenningBalance` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccount` MODIFY COLUMN `LastModifiedOn` datetime NOT NULL;
ALTER TABLE `paymentaccountedit` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `paymentaccountedit` MODIFY COLUMN `PaymentAccount_Id` longtext;
ALTER TABLE `paymentaccountedit` MODIFY COLUMN `Initial_Balance` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccountedit` MODIFY COLUMN `Adjusted_Amount` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `ByInvoice` tinyint(1) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `Description` longtext;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `PaymentAccountId` longtext;
ALTER TABLE `paymentaccountoperation` ADD COLUMN `RefId` longtext;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `TransactionType` longtext;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `IsCredit` tinyint(1) NOT NULL;
ALTER TABLE `paymentaccountoperation` MODIFY COLUMN `CustomerId` longtext;
ALTER TABLE `product` MODIFY COLUMN `Category` longtext NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Shelf` longtext NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `ReorderLevel` decimal(18,2) NOT NULL;
ALTER TABLE `product` ADD COLUMN `MaxorderLevel` decimal(18,2) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Service` tinyint(1) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Active` tinyint(1) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `product` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Price1` decimal(18,2) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Price2` decimal(18,2) NOT NULL;
ALTER TABLE `product` MODIFY COLUMN `Price3` decimal(18,2) NOT NULL;
ALTER TABLE `product` ADD COLUMN `Sellable` tinyint(1);
ALTER TABLE `product` ADD COLUMN `Purchasable` tinyint(1);
ALTER TABLE `product` ADD COLUMN `Taxable` tinyint(1);
ALTER TABLE `product` ADD COLUMN `Attributes` text;
ALTER TABLE `product` ADD COLUMN `Weight` float;
ALTER TABLE `product` ADD COLUMN `Backorders` tinyint(1);
ALTER TABLE `productcategory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productcategory` MODIFY COLUMN `Name` longtext;
ALTER TABLE `productcategory` MODIFY COLUMN `Description` longtext;
ALTER TABLE `productcategory` MODIFY COLUMN `ProfileImage` longblob;
CREATE TABLE `productedit` (`Id` varchar(128) NOT NULL, `Product_Code` longtext, `Initial_Balance` decimal(18,2) NOT NULL, `Adjusted_Qty` decimal(18,2) NOT NULL, `CreatedOn` datetime NOT NULL);
ALTER TABLE `producthistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `producthistory` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `producthistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `producthistory` MODIFY COLUMN `AvailableQty` double NOT NULL;
ALTER TABLE `producthistory` MODIFY COLUMN `Quantity` double NOT NULL;
ALTER TABLE `producthistory` MODIFY COLUMN `amount` decimal(18,2) NOT NULL;
CREATE TABLE `production` (`Id` varchar(36), `Comment` varchar(250), `UserId` varchar(36), `CreatedOn` datetime, `LastModifiedOn` datetime);
CREATE TABLE `productionrecord` (`Id` varchar(36), `ProductionId` int(11), `ProductId` varchar(36), `AvailQty` float, `Qty` float, `Price` float, `Amount` float);
ALTER TABLE `productprice` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productprice` MODIFY COLUMN `PriceTypeId` longtext;
ALTER TABLE `productprice` MODIFY COLUMN `ProductCode` longtext;
ALTER TABLE `productprice` MODIFY COLUMN `Price` decimal(18,2) NOT NULL;
ALTER TABLE `productpricetype` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productpricetype` MODIFY COLUMN `Name` longtext;
ALTER TABLE `productpricetype` MODIFY COLUMN `CreatedOn` datetime;
ALTER TABLE `productstock` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productstock` MODIFY COLUMN `RefId` longtext;
ALTER TABLE `productstock` MODIFY COLUMN `ProductCode` longtext;
ALTER TABLE `productstock` MODIFY COLUMN `AvailableQuantity` decimal(18,2) NOT NULL;
ALTER TABLE `productstock` MODIFY COLUMN `ActualQuantity` decimal(18,2) NOT NULL;
ALTER TABLE `productstock` MODIFY COLUMN `UpdatedBy` longtext;
ALTER TABLE `productstock` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `RefId` longtext;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `AdjustedQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `Price1` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `Price2` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `Price3` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `ReorderLevel` decimal(18,2) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `Reason` longtext;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `IsInward` tinyint(1) NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `CreatedOn` datetime NOT NULL;
ALTER TABLE `productstockadjustment` MODIFY COLUMN `UpdatedBy` longtext;
ALTER TABLE `productstockdead` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productstockdead` MODIFY COLUMN `RefId` longtext;
ALTER TABLE `productstockdead` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `productstockdead` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstockdead` MODIFY COLUMN `DeadQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstockdead` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `productstockdead` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `productstockdead` MODIFY COLUMN `Reason` longtext;
ALTER TABLE `productstockdead` MODIFY COLUMN `UpdatedBy` longtext;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `RefId` longtext;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `AdjustedQty` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `Price1` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `Price2` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `Price3` decimal(18,2) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `ReorderLevel` decimal(18,2);
ALTER TABLE `productstocktransfer` MODIFY COLUMN `Reason` longtext;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `IsInward` tinyint(1) NOT NULL;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `UpdatedBy` longtext;
ALTER TABLE `productstocktransfer` MODIFY COLUMN `BranchId` longtext;
ALTER TABLE `productstockvalue` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `productstockvalue` MODIFY COLUMN `StockValue` decimal(18,2) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `purchasehistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `purchasehistory` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `CostPrice` decimal(18,2) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `purchasehistory` MODIFY COLUMN `ReorderLevel` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `TransactionId` varchar(128) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `SupplierId` longtext;
ALTER TABLE `purchases` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `purchases` MODIFY COLUMN `PaymentMethod` longtext;
ALTER TABLE `purchases` MODIFY COLUMN `InvoiceTotal` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `Discount` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `Tax` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `NetTotal` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `Paid` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `ItemCount` int(11) NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `Description` longtext;
ALTER TABLE `purchases` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `purchases` ADD COLUMN `SaleDate` datetime NOT NULL;
ALTER TABLE `purchases` MODIFY COLUMN `IsVoided` tinyint(1) NOT NULL;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `CustomerId` longtext;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `InvoiceId` longtext;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `AmountReturned` decimal(18,2) NOT NULL;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `PaymentMethod` longtext;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `Description` longtext;
ALTER TABLE `purchasesreturn` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `purchasesreturn` ADD COLUMN `Purchase Date` datetime NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `Price` decimal(18,2) NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `CreatedOn` datetime NOT NULL;
ALTER TABLE `purchasesreturnhistory` MODIFY COLUMN `LastModifiedOn` datetime;
ALTER TABLE `sales` MODIFY COLUMN `TransactionId` varchar(128) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `CustomerId` longtext;
ALTER TABLE `sales` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `sales` MODIFY COLUMN `InvoiceTotal` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `Discount` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `Tax` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `NetTotal` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `Paid` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `PaymentMethod` longtext;
ALTER TABLE `sales` MODIFY COLUMN `Description` longtext;
ALTER TABLE `sales` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `sales` ADD COLUMN `SaleDate` datetime NOT NULL;
ALTER TABLE `sales` MODIFY COLUMN `IsVoided` tinyint(1) NOT NULL;
ALTER TABLE `saleshistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `saleshistory` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `saleshistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `saleshistory` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `saleshistory` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `saleshistory` MODIFY COLUMN `Price` decimal(18,2) NOT NULL;
ALTER TABLE `saleshistory` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `salesreturn` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `salesreturn` MODIFY COLUMN `CustomerId` longtext;
ALTER TABLE `salesreturn` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `salesreturn` MODIFY COLUMN `InvoiceId` longtext;
ALTER TABLE `salesreturn` MODIFY COLUMN `AmountReturned` decimal(18,2) NOT NULL;
ALTER TABLE `salesreturn` MODIFY COLUMN `PaymentMethod` longtext;
ALTER TABLE `salesreturn` MODIFY COLUMN `Description` longtext;
ALTER TABLE `salesreturn` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `salesreturn` ADD COLUMN `SaleDate` datetime NOT NULL;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `Price` decimal(18,2) NOT NULL;
ALTER TABLE `salesreturnhistory` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `TransactionId` varchar(128);
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `AvailableQty` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `Quantity` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `Price` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_history_table` MODIFY COLUMN `Amount` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `TransactionId` varchar(128) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `CustomerId` longtext;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `UserId` longtext;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `InvoiceTotal` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `Discount` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `Tax` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `NetTotal` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `Paid` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `PaymentMethod` longtext;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `PriceType` longtext;
ALTER TABLE `sales_cart_table` MODIFY COLUMN `Description` longtext;
ALTER TABLE `sales_cart_table` ADD COLUMN `SaleDate` datetime NOT NULL;
ALTER TABLE `settings` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `settings` MODIFY COLUMN `Name` longtext;
ALTER TABLE `settings` MODIFY COLUMN `Value` longtext;
ALTER TABLE `shelf` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `shelf` MODIFY COLUMN `Number` longtext;
ALTER TABLE `shelf` MODIFY COLUMN `Description` longtext;
ALTER TABLE `stockhistory` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `stockhistory` MODIFY COLUMN `ProductId` longtext;
ALTER TABLE `stockhistory` MODIFY COLUMN `amount` decimal(18,2) NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `Name` longtext;
ALTER TABLE `supplier` MODIFY COLUMN `Phone` longtext;
ALTER TABLE `supplier` MODIFY COLUMN `Email` longtext;
ALTER TABLE `supplier` MODIFY COLUMN `Address` longtext;
ALTER TABLE `supplier` MODIFY COLUMN `OpenningBalance` decimal(18,2) NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `Balance` decimal(18,2) NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `CreditAllowanceDays` int(11) NOT NULL;
ALTER TABLE `supplier` MODIFY COLUMN `Active` tinyint(1) NOT NULL;
ALTER TABLE `supplieredit` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `supplieredit` MODIFY COLUMN `Supplier_Id` longtext;
ALTER TABLE `supplieredit` MODIFY COLUMN `Initial_Balance` decimal(18,2) NOT NULL;
ALTER TABLE `supplieredit` MODIFY COLUMN `Adjusted_Amount` decimal(18,2) NOT NULL;
ALTER TABLE `user` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `user` MODIFY COLUMN `FirstName` longtext;
ALTER TABLE `user` MODIFY COLUMN `LastName` longtext;
ALTER TABLE `user` MODIFY COLUMN `Phone` longtext;
ALTER TABLE `user` MODIFY COLUMN `Email` longtext;
ALTER TABLE `user` MODIFY COLUMN `Address` longtext;
ALTER TABLE `user` MODIFY COLUMN `Username` longtext;
ALTER TABLE `user` MODIFY COLUMN `Password` longtext;
ALTER TABLE `user` MODIFY COLUMN `ProfileImage` longblob;
ALTER TABLE `userpermission` MODIFY COLUMN `Id` varchar(128) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `FEATURES` longtext;
ALTER TABLE `userpermission` MODIFY COLUMN `DIRECTOR` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `ADMIN` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `SALES` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `PURCHASE` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `MANAGER` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `ACCOUNTANT` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `CASHIER` tinyint(1) NOT NULL;
ALTER TABLE `userpermission` MODIFY COLUMN `STOCKKEEPER` tinyint(1) NOT NULL;
CREATE TABLE `__migrationhistory` (`MigrationId` varchar(150) NOT NULL, `ContextKey` varchar(300) NOT NULL, `Model` longblob NOT NULL, `ProductVersion` varchar(32) NOT NULL);
DROP TABLE `otheraccountpaymentoperationtable`;
DROP TABLE `otheraccounttable`;
ALTER TABLE `sales_cart_history_table` DROP COLUMN `Synced`;
ALTER TABLE `sales_cart_table` DROP COLUMN `SalesDate`;
ALTER TABLE `sales_cart_table` DROP COLUMN `Synced`;
ALTER TABLE `branchedit` DROP COLUMN `Synced`;
ALTER TABLE `branchexportoperation` DROP COLUMN `ReferenceId`;
ALTER TABLE `branchexportoperation` DROP COLUMN `Synced`;
ALTER TABLE `branchexport` DROP COLUMN `Synced`;
ALTER TABLE `branchimportoperation` DROP COLUMN `ReferenceId`;
ALTER TABLE `branchimportoperation` DROP COLUMN `Synced`;
ALTER TABLE `branchimport` DROP COLUMN `Synced`;
ALTER TABLE `branchpaymentoperation` DROP COLUMN `ReferenceId`;
ALTER TABLE `branchpaymentoperation` DROP COLUMN `Synced`;
ALTER TABLE `branch` DROP COLUMN `Synced`;
ALTER TABLE `customeraccounttransfer` DROP COLUMN `Synced`;
ALTER TABLE `customeredit` DROP COLUMN `Synced`;
ALTER TABLE `customer` DROP COLUMN `Synced`;
ALTER TABLE `expense` DROP COLUMN `Synced`;
ALTER TABLE `expensetype` DROP COLUMN `Synced`;
ALTER TABLE `paymentaccountedit` DROP COLUMN `Synced`;
ALTER TABLE `paymentaccountoperation` DROP COLUMN `ReferenceId`;
ALTER TABLE `paymentaccountoperation` DROP COLUMN `Synced`;
ALTER TABLE `paymentaccount` DROP COLUMN `Synced`;
ALTER TABLE `productcategory` DROP COLUMN `Synced`;
ALTER TABLE `producthistory` DROP COLUMN `Synced`;
ALTER TABLE `productprice` DROP COLUMN `Synced`;
ALTER TABLE `productpricetype` DROP COLUMN `Synced`;
ALTER TABLE `productstockadjustment` DROP COLUMN `Synced`;
ALTER TABLE `productstockdead` DROP COLUMN `Synced`;
ALTER TABLE `productstock` DROP COLUMN `Synced`;
ALTER TABLE `productstocktransfer` DROP COLUMN `Synced`;
ALTER TABLE `productstockvalue` DROP COLUMN `Synced`;
ALTER TABLE `product` DROP COLUMN `Synced`;
ALTER TABLE `purchasehistory` DROP COLUMN `Synced`;
ALTER TABLE `purchasesreturnhistory` DROP COLUMN `Synced`;
ALTER TABLE `purchasesreturn` DROP COLUMN `Purchases Date`;
ALTER TABLE `purchasesreturn` DROP COLUMN `Synced`;
ALTER TABLE `purchases` DROP COLUMN `SalesDate`;
ALTER TABLE `purchases` DROP COLUMN `Synced`;
ALTER TABLE `saleshistory` DROP COLUMN `Synced`;
ALTER TABLE `salesreturnhistory` DROP COLUMN `Synced`;
ALTER TABLE `salesreturn` DROP COLUMN `SalesDate`;
ALTER TABLE `salesreturn` DROP COLUMN `Synced`;
ALTER TABLE `sales` DROP COLUMN `SalesDate`;
ALTER TABLE `sales` DROP COLUMN `Synced`;
ALTER TABLE `settings` DROP COLUMN `Synced`;
ALTER TABLE `shelf` DROP COLUMN `Synced`;
ALTER TABLE `stockhistory` DROP COLUMN `Synced`;
ALTER TABLE `supplieredit` DROP COLUMN `Synced`;
ALTER TABLE `supplier` DROP COLUMN `Synced`;
ALTER TABLE `userpermission` DROP COLUMN `Synced`;
ALTER TABLE `user` DROP COLUMN `Synced`;
COMMIT;
